### ISSUE TITLE
Error when loading jit model

### ISSUE THREAD

**Issue by xungeer29** [FacePerceiver/facer#1]
when run `face_parser = facer.face_parser('farl/lapa/448', device='cuda')`
Error:
```bash
  File "facer/facer/util.py", line 79, in download_jit
    return torch.jit.load(cached_file, map_location=map_location)
  File "anaconda3/lib/python3.6/site-packages/torch/jit/_serialization.py", line 161, in load
    cpp_module = torch._C.import_ir_module(cu, f, map_location, _extra_files)
RuntimeError: 
Unknown type name 'NoneType':
Serialized   File "code/__torch__/farl/network/transformers.py", line 7
  image_std : Tensor
  training : bool
  _is_full_backward_hook : NoneType
                           ~~~~~~~~ <--- HERE
  num_extra_tokens : int
  input_resolution : int
```
Envs:
torch=1.7.1
torchvision=0.8.2
cuda=11.0
RTX 3090

**Comment by greecehalf** [comment]
It seems like just happened.

**Comment by xasd2003** [comment]
+1

**Comment by tegusi** [comment]
I encountered this error:

``
Unknown builtin op: aten::reflection_pad3d.
Here are some suggestions: 
	aten::reflection_pad2d
	aten::reflection_pad1d
``

under environment
torch=1.9.0+cu10.2

**Comment by JACKYLUO1991** [comment]
@tegusi I encountered the same problem as you， torch==1.10+cu11.1. How did you deal with it later?

**Comment by YANG-H** [comment]
Hi all, sorry for the late response. It should be due to that the jit models are generated using the latest version of PyTorch. 
Please try re-installing the facer package using `python setup.py install` and see if the errors still exist.

**Comment by JACKYLUO1991** [comment]
@YANG-H Is it convenient to provide the jit of torch1.9.1+cuda11.1? Replace cuda so troublesome, many software is not compatible.

**Comment by YANG-H** [comment]
We will work on this. It may take some time.

> @YANG-H Is it convenient to provide the jit of torch1.9.1+cuda11.1? Replace cuda so troublesome, many software is not compatible.

**Comment by YANG-H** [comment]
> @YANG-H Is it convenient to provide the jit of torch1.9.1+cuda11.1? Replace cuda so troublesome, many software is not compatible.

Hi, we have added support for torch-1.9.1, please try using the last main branch. Thanks.
