### ISSUE TITLE
Questions about what labels mean

### ISSUE THREAD

**Issue by skyking-317** [FacePerceiver/facer#20]
Can you tell me the full meanings of these labels.
'background', 'neck', 'face', 'cloth', 'rr', 'lr', 'rb', 'lb', 're', 'le', 'nose', 'imouth', 'llip', 'ulip', 'hair', 'eyeg', 'hat', 'earr', 'neck_l'

Abbreviations like rr give me a bit of trouble.

**Comment by Ttayu** [comment]
- neck
- face
- cloth
- right ear
- left ear
- right eyebrow
- left eyebrow
- right eye
- left eye
- nose
- mouth
- lower lip
- upper lip
- hair
- eyeglass
- hat
- earring
- necklace
