### ISSUE TITLE
Face parsing model on celebm is not available

### ISSUE THREAD

**Issue by caopulan** [FacePerceiver/facer#3]
Face parsing model trained on celebm is deleted in this commit "ab13b31c9d81e4d584a3cb0ca14e9cd22c7292e2".

**Comment by Bai426** [comment]
Why there are not 19 segmentation classes with celebA_HQ model? And there are less than 12 segmentation classes for the provided model in facer?

**Comment by YANG-H** [comment]
The CelebAMaskHQ is not yet ready to use. Please refer to https://github.com/FacePerceiver/facer/issues/8#issuecomment-1460660369

**Comment by Bai426** [comment]
Thank you very much! I think this pretrained model of celebA (https://github.com/FacePerceiver/facer/releases/download/models-v1/face_parsing.farl.celebm.main_ema_181500_jit.pt) is good.

**Comment by JinEui-Kim** [comment]
> Thank you very much! I think this pretrained model of celebA (https://github.com/FacePerceiver/facer/releases/download/models-v1/face_parsing.farl.celebm.main_ema_181500_jit.pt) is good.

Thanks. It works for me.
I just change the url of pretrain_settings in file '~/anaconda3/envs/fran/lib/python3.9/site-packages/facer/face_parsing/farl.py', line 14. like below
```
pretrain_settings = {
    'lapa/448': {
        'url': [
            # original
            # 'https://github.com/FacePerceiver/facer/releases/download/models-v1/face_parsing.farl.lapa.main_ema_136500_jit191.pt',
            'https://github.com/FacePerceiver/facer/releases/download/models-v1/face_parsing.farl.celebm.main_ema_181500_jit.pt',
        ],
        'matrix_src_tag': 'points',
        'get_matrix_fn': functools.partial(get_face_align_matrix,
                                           target_shape=(448, 448), target_face_scale=1.0),
        'get_grid_fn': functools.partial(make_tanh_warp_grid,
                                         warp_factor=0.8, warped_shape=(448, 448)),
        'get_inv_grid_fn': functools.partial(make_inverted_tanh_warp_grid,
                                             warp_factor=0.8, warped_shape=(448, 448)),
        'label_names': ['background', 'face', 'rb', 'lb', 're',
                        'le', 'nose',  'ulip', 'imouth', 'llip', 'hair']
    }
}
```

then i got the face and neck mask.
![화면 캡처 2023-03-29 151732](https://user-images.githubusercontent.com/114208539/228443292-ef3a12b1-c26b-42de-b694-3f44054c5f53.jpg)

**Comment by yinglinzheng** [comment]
Hi, celebm face parsing model is available , try it out [here](https://github.com/FacePerceiver/facer/blob/main/samples/face_parsing.ipynb)
