### ISSUE TITLE
Will the Ear output be available

### ISSUE THREAD

**Issue by VCasecnikovs** [FacePerceiver/facer#7]
Hi!
Thank you for your work. 
Will the ear segmentation be available after some time?
As I understand, ear segmentation is needed for the Celeb-A-HQ-Mask dataset, but I can not find it in the current "Facer" implementation?

Best regards,
Vadims.

**Comment by yinglinzheng** [comment]
Hi, celebm face parsing model is available, try it out [here](https://github.com/FacePerceiver/facer/blob/main/samples/face_parsing.ipynb)
