### ISSUE TITLE
Is the repo going to be updated?

### ISSUE THREAD

**Issue by wamiq-reyaz** [FacePerceiver/facer#8]
Hey all.

This is a very performant repository. 

I wanted masks in the style of CelebA (with neck, clothing, hats etc). The FaRL repo already has those models.

Are they going to be updated anytime soon, or can we consider this repo to be abandoned?

Best,
Wamiq

**Comment by YANG-H** [comment]
Sorry for the bothering. The FaRL parsing on CelebAMaskHQ is trained directly on CelebAMaskHQ images without five point alignment. We have to figure out how CelebAMaskHQ images are aligned and cropped first before wrapping the face parser into facer, which would be in a while.

**Comment by yinglinzheng** [comment]
Hi, celebm face parsing model is available, try it out [here](https://github.com/FacePerceiver/facer/blob/main/samples/face_parsing.ipynb)
